<h1 style='color:red'>GOOD EVENING</h1>

<h2 style='color:#123456'>PUT YOUR DOUBTS IN CHAT??</h2>

In [3]:
import numpy as np
import random

def with_lists(l1, l2):
    ALPHA = [[random.uniform(0, 1) for k in range(l2)] for l in range(l1)]
    COEFF = [[random.uniform(0, 1) for k in range(l2)] for l in range(l1)]
    summa=0.0
    for l in range(l1):
        for k in range(l2):
            summa+=COEFF[l][k] * ALPHA[l][k]
    return summa

def with_arrays(l1, l2):
    ALPHA = np.random.uniform(size=(l1,l2))
    COEFF = np.random.uniform(size=(l1,l2))
    summa=0.0
    for l in range(l1):
        for k in range(l2):
            summa+=COEFF[l][k] * ALPHA[l][k]
    return summa



In [4]:
%%timeit 
with_lists(10, 10)

99.5 µs ± 3.57 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [5]:
%%timeit 
with_arrays(10, 10)

108 µs ± 5.14 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


    [
        [1, 2, 3, 4]
        [3, 4, 5, 6]
        [6, 7, 8, 9]
    ]

In [10]:
def matrix(row, col):
    m = []
    for r in range(row):
        l = []
        for c in range(col):
            l.append(int(input(f"\n Element {[r]}{[c]} --> ")))
        m.append(l)
    return m

In [13]:
m = matrix(2, 2)


 Element [0][0] --> 3

 Element [0][1] --> 4

 Element [1][0] --> 5

 Element [1][1] --> 6


                                | 3  4 |
                                | 5  6 |

In [88]:
def matrix(row, col):
    m = [[int(input(f"ELEMENT {[r]}{[c]} --> ")) for c in range(col)] for r in range(row)]
    return m
matrix(2, 2)

ELEMENT [0][0] --> 2
ELEMENT [0][1] --> 3
ELEMENT [1][0] --> 1
ELEMENT [1][1] --> 2


[[2, 3], [1, 2]]

In [16]:
def show_matrix(mat):
    for i in mat:
        print(*i, sep="|")
        
show_matrix(m)

3|4
5|6


In [19]:
def show_matrix(mat):
    for i in mat:
        print("|", *i,"|")
        
show_matrix(m)

| 3 4 |
| 5 6 |


In [21]:
arr = np.random.randint(1, 10, 15)

In [22]:
arr.ndim

1

In [23]:
arr.size

15

In [24]:
arr.shape

(15,)

In [27]:
arr2 = arr.reshape(5, 3)  # 15 elements --> 5*3, 3*5

In [28]:
arr2

array([[1, 8, 9],
       [7, 7, 2],
       [3, 3, 2],
       [7, 9, 5],
       [4, 7, 4]])

In [29]:
arr2.shape

(5, 3)

In [30]:
import random

In [42]:
random.randrange(2, 11, 2)  # 2, 4, 6, 8, 10

10

In [43]:
arr2.ndim

2

In [44]:
l = [1, 2, 3, 4]

In [48]:
[1, 2, 3, 4][True]

2

In [51]:
arr2[0][1]

8

In [55]:
l = [[1, 8, 9],
    [7, 7, 2],
    [3, 3, 2],
    [7, 9, 5],
    [4, 7, 4]]

In [56]:
l

[[1, 8, 9], [7, 7, 2], [3, 3, 2], [7, 9, 5], [4, 7, 4]]

In [58]:
l[:][1]

[7, 7, 2]

In [52]:
arr2

# 8, 7, 3, 9, 7

array([[1, 8, 9],
       [7, 7, 2],
       [3, 3, 2],
       [7, 9, 5],
       [4, 7, 4]])

In [62]:
arr2[::-1]

array([[4, 7, 4],
       [7, 9, 5],
       [3, 3, 2],
       [7, 7, 2],
       [1, 8, 9]])

In [63]:
arr2[::-1][::-1]

array([[1, 8, 9],
       [7, 7, 2],
       [3, 3, 2],
       [7, 9, 5],
       [4, 7, 4]])

    arr2[row_slicing, column_slicing]

In [67]:
arr2[::-1]

array([[4, 7, 4],
       [7, 9, 5],
       [3, 3, 2],
       [7, 7, 2],
       [1, 8, 9]])

In [68]:
arr2[::-1, 1]

array([7, 9, 3, 7, 8])

In [69]:
arr2[:, 1]

array([8, 7, 3, 9, 7])

In [70]:
arr2

array([[1, 8, 9],
       [7, 7, 2],
       [3, 3, 2],
       [7, 9, 5],
       [4, 7, 4]])

In [71]:
arr2[::2, ::2]

array([[1, 9],
       [3, 2],
       [4, 4]])

In [73]:
arr2[[1, 3, 4], 2]

array([2, 5, 4])

In [75]:
arr2[0][1]

8

In [77]:
arr2[0, 1]

8

In [78]:
arr1 = np.random.randint(1, 20, 50).reshape(10, 5)

In [79]:
arr1

array([[ 6,  7, 18,  6,  4],
       [ 6,  5,  2,  8, 12],
       [19,  5,  8,  5, 17],
       [15, 10, 16, 11, 19],
       [15,  1,  9,  4, 17],
       [14,  6, 13, 11,  5],
       [ 1, 18,  7,  7, 16],
       [10, 14,  9,  6,  4],
       [19, 12, 15,  8, 10],
       [ 7, 19,  4, 17,  8]])

In [81]:
arr1[-1:-4:-1]

array([[ 7, 19,  4, 17,  8],
       [19, 12, 15,  8, 10],
       [10, 14,  9,  6,  4]])

In [82]:
arr1[-1:-8:-2, [1, 3, 4]]

array([[19, 17,  8],
       [14,  6,  4],
       [ 6, 11,  5],
       [10, 11, 19]])

In [84]:
arr1[::-1, ::-1]

array([[ 8, 17,  4, 19,  7],
       [10,  8, 15, 12, 19],
       [ 4,  6,  9, 14, 10],
       [16,  7,  7, 18,  1],
       [ 5, 11, 13,  6, 14],
       [17,  4,  9,  1, 15],
       [19, 11, 16, 10, 15],
       [17,  5,  8,  5, 19],
       [12,  8,  2,  5,  6],
       [ 4,  6, 18,  7,  6]])

In [85]:
arr1[[2, 4, 5, 9], ::-1]

array([[17,  5,  8,  5, 19],
       [17,  4,  9,  1, 15],
       [ 5, 11, 13,  6, 14],
       [ 8, 17,  4, 19,  7]])

### 3D array

    Collection of 2D array
    
    
        [
            [
                [1, 2, 3],
                [2, 3, 4]
             ],
             [
                [1, 2, 3],
                [2, 3, 4]
             ]
        ]

### write code to create 3d array using list comprehension

In [98]:
l1 = [
        [
            [1, 2, 3],
            [2, 3, 4]
         ],
         [
            [11, 21, 31],
            [12, 13, 14]
         ]
    ]
arr3 = np.array(l1)

In [99]:
arr3

array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[11, 21, 31],
        [12, 13, 14]]])

In [100]:
arr3.ndim

3

In [101]:
arr3.shape
# (no_of_2d_array, no_of_rows, no_of_cols)

(2, 2, 3)

In [102]:
arr3.size # 2*2*3

12

In [103]:
arr3

array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[11, 21, 31],
        [12, 13, 14]]])

In [106]:
arr3[0][1][1]

3

In [110]:
arr3[::-1][0][1][-1]

14

In [ ]:
arr3[2d_array, row, col]

In [113]:
arr3[0, 1, 2]

4

In [116]:
arr3[::-1, 1, ::-1]

array([[14, 13, 12],
       [ 4,  3,  2]])

In [117]:
arr3[:, 1, [1, 2]]

array([[ 3,  4],
       [13, 14]])

In [120]:
arr3d = np.random.randint(1, 20, (4, 4, 5))

In [121]:
arr3d

array([[[ 6,  2, 16,  3,  6],
        [15, 14, 13, 18,  4],
        [19,  8,  8,  3,  6],
        [ 9, 13,  2, 12, 18]],

       [[ 3, 14,  1,  9, 12],
        [ 3, 19,  1, 13, 15],
        [10,  3,  3, 13, 17],
        [12, 13, 15, 18,  8]],

       [[13, 11, 11, 15,  1],
        [16,  3,  2,  9, 18],
        [ 7, 17, 14,  1,  3],
        [15, 15, 12,  1,  7]],

       [[14,  1,  6,  4, 10],
        [12,  4, 10,  7, 16],
        [12, 10, 11,  4,  9],
        [16,  2,  6, 18, 13]]])

In [122]:
arr3d[::2, [1, 3], -1:2]

array([], shape=(2, 2, 0), dtype=int32)

In [123]:
arr3d[::2, [1, 3], -1:2:-1]

array([[[ 4, 18],
        [18, 12]],

       [[18,  9],
        [ 7,  1]]])