<h1 style='color:red'>GOOD EVENING</h1>

<h2>Doubts???</h2>

In [1]:
import numpy as np

In [7]:
def array(dim = None):
    if dim == 1:
        num = int(input("\n Enter size of array --> "))
        return np.array([int(input(f"\n Enter elements {i} --> ")) for i in range(1, num+1)])
    elif dim == 2:
        row, col = int(input("\n Enter rows : ")), int(input("\n Enter columns : "))
        return np.array([[int(input(f"\n Element [{r}][{c}] --> ")) for c in range(col)] for r in range(row)])
    elif dim == 3:
        arr = int(input("\n Enter number of 2d array --> "))
        row, col = int(input("\n Enter rows : ")), int(input("\n Enter columns : "))
        return np.array([[[int(input(f"\n Element [{a}][{r}][{c}] --> ")) for c in range(col)] 
                         for r in range(row)] for a in range(arr)])

In [8]:
array(3)


 Enter number of 2d array --> 2

 Enter rows : 2

 Enter columns : 2

 Element [0][0][0] --> 1

 Element [0][0][1] --> 2

 Element [0][1][0] --> 3

 Element [0][1][1] --> 4

 Element [1][0][0] --> 5

 Element [1][0][1] --> 11

 Element [1][1][0] --> 12

 Element [1][1][1] --> 13


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5, 11],
        [12, 13]]])

In [ ]:
a = int(input()); b = int(input())

In [3]:
a

10

In [4]:
b

20

In [10]:
arr1 = np.random.randint(1, 30, (3, 4, 3))

In [11]:
arr1.shape

(3, 4, 3)

In [12]:
arr1.ndim

3

In [13]:
arr1

array([[[ 9, 25,  8],
        [25, 20,  7],
        [13, 29,  7],
        [ 8, 14, 18]],

       [[ 1, 19, 11],
        [ 1, 14, 27],
        [16, 28, 16],
        [25, 21, 22]],

       [[20, 29, 20],
        [12,  3, 21],
        [ 2, 14, 26],
        [ 1,  8,  7]]])

In [18]:
arr1[::-1, [2, 3]]

array([[[ 2, 14, 26],
        [ 1,  8,  7]],

       [[16, 28, 16],
        [25, 21, 22]],

       [[13, 29,  7],
        [ 8, 14, 18]]])

In [22]:
arr1[::-1, [2, 3], [0, 1, 2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [23]:
arr1[::-1, [1, 2, 3], [0, 1, 2]]

array([[12, 14,  7],
       [ 1, 28, 22],
       [25, 29, 18]])

In [20]:
arr1[::-1, [2, 3], [-1, -2]]

array([[26,  8],
       [16, 21],
       [ 7, 14]])

In [24]:
type(arr1.shape)

tuple

## Numpy Operations

In [25]:
a1 = np.random.randint(1, 10, 10)
a2 = np.random.randint(1, 20, 10)

In [26]:
a1 + a2  # element wise addition

array([19, 24, 22, 19, 16,  8, 20, 11,  7, 16])

In [27]:
a1

array([1, 5, 3, 9, 1, 1, 7, 1, 1, 3])

In [29]:
a2

array([18, 19, 19, 10, 15,  7, 13, 10,  6, 13])

In [30]:
a1*2

array([ 2, 10,  6, 18,  2,  2, 14,  2,  2,  6])

In [31]:
a1//3

array([0, 1, 1, 3, 0, 0, 2, 0, 0, 1], dtype=int32)

In [32]:
a1**4

array([   1,  625,   81, 6561,    1,    1, 2401,    1,    1,   81],
      dtype=int32)

In [33]:
a1*a2  # element wise multiplication

array([18, 95, 57, 90, 15,  7, 91, 10,  6, 39])

In [35]:
a1//a2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [36]:
a1%6

array([1, 5, 3, 3, 1, 1, 1, 1, 1, 3], dtype=int32)

In [38]:
(a1/a2)%2

array([0.05555556, 0.26315789, 0.15789474, 0.9       , 0.06666667,
       0.14285714, 0.53846154, 0.1       , 0.16666667, 0.23076923])

In [40]:
a1 > 2

array([False,  True,  True,  True, False, False,  True, False, False,
        True])

In [41]:
[1, 2, 3, 4, 5][True]  # True --> 1, False --> 0

2

In [42]:
[1, 2, 3, 4] > 4

TypeError: '>' not supported between instances of 'list' and 'int'

In [43]:
[1, 2, 3, 4] > [3, 4, 5]

False

In [44]:
a1 > 2
# True --> elements > 2 
# False --> element < 2

array([False,  True,  True,  True, False, False,  True, False, False,
        True])

In [47]:
a1

array([1, 5, 3, 9, 1, 1, 7, 1, 1, 3])

In [48]:
a1[[True, False, True, False, False, True, False, True, False, True]]

array([1, 3, 1, 1, 3])

In [50]:
a1[a1>2]

array([5, 3, 9, 7, 3])

In [52]:
a2[a2%2 == 0]

array([18, 10, 10,  6])

In [55]:
a1

array([1, 5, 3, 9, 1, 1, 7, 1, 1, 3])

In [60]:
a2

array([18, 19, 19, 10, 15,  7, 13, 10,  6, 13])

In [57]:
a1[[1, 0, 1]]

array([5, 1, 5])

In [63]:
arr1.size

36

In [62]:
arr1[[0, 1]]

array([[[ 9, 25,  8],
        [25, 20,  7],
        [13, 29,  7],
        [ 8, 14, 18]],

       [[ 1, 19, 11],
        [ 1, 14, 27],
        [16, 28, 16],
        [25, 21, 22]]])

In [64]:
arr2 = arr1.reshape(6, 6)

In [67]:
arr2[[1, 3, 4]]

array([[13, 29,  7,  8, 14, 18],
       [16, 28, 16, 25, 21, 22],
       [20, 29, 20, 12,  3, 21]])

In [69]:
a1[[0, 1, 3]]

array([1, 5, 9])

In [73]:
a1[(a1*a2)>30]

array([5, 3, 9, 7, 3])

In [75]:
a2[a1>2]

array([19, 19, 10, 13, 13])

In [79]:
name = np.array(list("abcdefghij"))
maths = np.random.randint(50, 100, 10)
sci = np.random.randint(50, 100, 10)
eng = np.random.randint(50, 100, 10)

In [80]:
name

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [81]:
len(name)

10

In [82]:
maths

array([98, 67, 95, 95, 52, 64, 53, 60, 93, 58])

In [83]:
sci

array([59, 73, 69, 92, 58, 87, 83, 98, 62, 90])

In [84]:
eng

array([95, 59, 78, 85, 96, 53, 83, 73, 50, 69])

In [86]:
name[maths>70]

array(['a', 'c', 'd', 'i'], dtype='<U1')

In [91]:
np.round((maths + sci + eng)/3, 2)

array([84.  , 66.33, 80.67, 90.67, 68.67, 68.  , 73.  , 77.  , 68.33,
       72.33])

In [92]:
[1, 2, 3, 4] and ([1, 2, 3, 4] or ())

[1, 2, 3, 4]

In [94]:
True and True

True

In [93]:
maths>70 and maths<=85

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [95]:
any(maths)
# return True if any of the value is True

True

In [96]:
all([0, 10, 1, 2])
# return True if all of the value is True

False

In [97]:
any([0, 10, 12, 34, False])

True

In [98]:
any(maths>70) and any(maths<=85)

True

In [102]:
(maths>70) and (maths<=85)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [105]:
(maths>70) & (maths<=85)

array([False, False, False, False, False, False, False, False, False,
       False])

In [103]:
maths

array([98, 67, 95, 95, 52, 64, 53, 60, 93, 58])

In [107]:
maths[(maths>70) & (maths<=95)]

array([95, 95, 93])

In [108]:
[0, 1, 2] and [3, 4, 1]

[3, 4, 1]

In [109]:
maths[(maths>70) | (maths<60)]

array([98, 95, 95, 52, 53, 93, 58])