### DOUBTS ???

### How many of you can take class at 8am raise your hand??

In [1]:
import numpy as np

In [2]:
np.ceil(2.78)

3.0

In [5]:
np.ceil(3)

3.0

In [6]:
np.ceil(2.4)

3.0

In [3]:
np.floor(2.78)

2.0

In [4]:
np.rint(2.78)

3.0

In [10]:
def do(mat1, mat2, operation):
    return [[eval(f"{mat1[i][j]} {operation} {mat2[i][j]}") for j in range(len(mat2[0]))] for i in range(len(mat1))]



a = np.random.randint(0, 10, (3,3))
b = np.random.randint(0, 10, (3,3))
do(a, b, "+")

[[17, 2, 7], [8, 15, 9], [0, 6, 8]]

In [15]:
i = 0

In [16]:
 [[eval(f"a[i][j] + b[i][j]") for j in range(len(b[0]))] for i in range(len(a))]

[[17, 2, 7], [17, 2, 7], [17, 2, 7]]

In [13]:
l = [1, 2, 3, 4]

In [14]:
func = "append"
eval("l.func(10)")

AttributeError: 'list' object has no attribute 'func'

### Numpy functions

In [17]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [18]:
np.arange(1, 11) # start, stop

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.arange(1, 30, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [20]:
np.arange(20, 0, -2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [21]:
np.arange(-1, -10)


array([], dtype=int32)

In [22]:
range(0.2, 0.8, 0.1)

TypeError: 'float' object cannot be interpreted as an integer

In [23]:
np.arange(0.2, 0.8, 0.1)

array([0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8])

In [24]:
0.2 + 0.1

0.30000000000000004

In [25]:
0.23 + 0.2

0.43000000000000005

In [26]:
1.45 + 1.5

2.95

In [29]:
np.arange(10, 100, 3).reshape(-1, 1)

array([[10],
       [13],
       [16],
       [19],
       [22],
       [25],
       [28],
       [31],
       [34],
       [37],
       [40],
       [43],
       [46],
       [49],
       [52],
       [55],
       [58],
       [61],
       [64],
       [67],
       [70],
       [73],
       [76],
       [79],
       [82],
       [85],
       [88],
       [91],
       [94],
       [97]])

In [30]:
np.arange(1, 100, (3, 3))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [31]:
np.arange((3, 3))

TypeError: arange: scalar arguments expected instead of a tuple.

In [32]:
np.linspace(-1, 1, 10)  # linear spaced data

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

In [33]:
0.77777778 - 1

-0.22222222000000003

In [34]:
0.55555556 - 0.77777778

-0.22222222000000003

In [35]:
 0.77777778 - 0.55555556

0.22222222000000003

In [36]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
np.linspace(1, 20, 9).reshape(1, -1)

array([[ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
        20.   ]])

In [41]:
arr = np.linspace(5, 10, 50)

In [42]:
arr.max()

10.0

In [43]:
arr

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [68]:
arr1 = np.random.randint(10, 60, 20)

In [69]:
arr1

array([16, 34, 12, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, 10])

In [70]:
arr1.max()

59

In [71]:
arr1.argmax()  # return the index of maximum element

7

In [72]:
arr1.min()

10

In [73]:
arr1.argmin()

19

In [74]:
arr1

array([16, 34, 12, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, 10])

In [75]:
min_ = arr1[0]
index = 0
for i in range(len(arr1)):
    if arr1[i] < min_:
        min_ = arr1[i]
        index = i

print(min_)
print(index)

10
19


In [76]:
def argmin(arr1):
    min_ = arr1[0]
    index = 0
    for i in range(len(arr1)):
        if arr1[i] < min_:
            min_ = arr1[i]
            index = i
    return (index)

In [77]:
argmin(arr1)

19

In [78]:
min_ = 0
for i in range(len(arr1)):
    if arr1[i] < arr1[min_]:
        min_ = i

In [79]:
min_

19

In [80]:
arr1

array([16, 34, 12, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, 10])

In [81]:
np.where(arr1)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19], dtype=int64),)

In [82]:
arr1

array([16, 34, 12, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, 10])

In [83]:
sorted(arr1)

[10,
 12,
 16,
 17,
 20,
 22,
 22,
 23,
 26,
 29,
 32,
 34,
 38,
 41,
 43,
 45,
 52,
 52,
 56,
 59]

In [65]:
arr1.sort()

In [66]:
arr1

array([10, 14, 20, 20, 21, 26, 27, 28, 32, 33, 36, 36, 37, 39, 41, 44, 45,
       50, 57, 57])

In [84]:
arr1.argsort() # return the indices of elements which you will get after sorting the array 

array([19,  2,  0, 10, 14,  6, 15, 11, 17,  4,  8,  1,  5,  9, 12, 16, 13,
        3, 18,  7], dtype=int64)

In [86]:
arr2 = np.random.randint(10, 50, (3, 3))

In [87]:
arr2

array([[33, 38, 33],
       [16, 28, 32],
       [23, 27, 18]])

In [90]:
arr2.max(axis=0)  # column wise maximum element

array([33, 38, 33])

In [91]:
arr2.max()

38

In [92]:
arr2.max(axis=1)  # row wise maximum element

array([38, 32, 27])

In [89]:
arr2.min()

16

In [93]:
arr2.min(axis=1)

array([33, 16, 18])

In [94]:
arr2.argmax()

1

In [95]:
arr2.argmax(axis=0)

array([0, 0, 0], dtype=int64)

In [96]:
arr2.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [97]:
arr2.sort()

In [98]:
arr2

array([[33, 33, 38],
       [16, 28, 32],
       [18, 23, 27]])

In [99]:
arr2.sort(axis=0)

In [100]:
arr2

array([[16, 23, 27],
       [18, 28, 32],
       [33, 33, 38]])

In [101]:
arr2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [102]:
np.where()

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [107]:
np.where(arr1>15)

(array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18], dtype=int64),)

In [105]:
arr1

array([16, 34, 12, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, 10])

In [110]:
np.where(arr1>15, arr1, arr1*2)

array([16, 34, 24, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, 20])

In [111]:
arr1*2

array([ 32,  68,  24, 104,  58,  76,  44, 118,  64,  82,  34,  46,  86,
       104,  40,  44,  90,  52, 112,  20])

In [112]:
arr1

array([16, 34, 12, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, 10])

In [113]:
np.where(arr1>50, arr1, arr1*2)

array([32, 68, 24, 52, 58, 76, 44, 59, 64, 82, 34, 46, 86, 52, 40, 44, 90,
       52, 56, 20])

In [114]:
np.where(arr1>15, arr1, -1)

array([16, 34, -1, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, -1])

In [116]:
np.where(arr1>50, arr1*2, -1)

array([ -1,  -1,  -1, 104,  -1,  -1,  -1, 118,  -1,  -1,  -1,  -1,  -1,
       104,  -1,  -1,  -1,  -1, 112,  -1])

In [143]:
np.where(arr1>50, arr1<70, arr1*2)

array([32, 68, 24,  1, 58, 76, 44,  1, 64, 82, 34, 46, 86,  1, 40, 44, 90,
       52,  1, 20])

In [145]:
arr1*2

array([ 32,  68,  24, 104,  58,  76,  44, 118,  64,  82,  34,  46,  86,
       104,  40,  44,  90,  52, 112,  20])

In [146]:
arr1

array([16, 34, 12, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, 10])

In [144]:
arr1<70

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [122]:
np.where(arr1>50, arr1<70, arr1)

array([16, 34, 12,  1, 29, 38, 22,  1, 32, 41, 17, 23, 43,  1, 20, 22, 45,
       26,  1, 10])

In [124]:
arr1

array([16, 34, 12, 52, 29, 38, 22, 59, 32, 41, 17, 23, 43, 52, 20, 22, 45,
       26, 56, 10])

In [125]:
a = arr1*2

In [126]:
a

array([ 32,  68,  24, 104,  58,  76,  44, 118,  64,  82,  34,  46,  86,
       104,  40,  44,  90,  52, 112,  20])

In [127]:
np.where(a>50, a<70, a)

array([32,  1, 24,  0,  1,  0, 44,  0,  1,  0, 34, 46,  0,  0, 40, 44,  0,
        1,  0, 20])

In [121]:
arr1*2

array([ 32,  68,  24, 104,  58,  76,  44, 118,  64,  82,  34,  46,  86,
       104,  40,  44,  90,  52, 112,  20])